"""Stub integration for Project 5 (Zero-Touch Telemetry)."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List


@dataclass
class ZeroTouchTelemetryStatus:
    status: str = "not_configured"
    detail: str = "Zero-Touch Telemetry integration pending implementation."


class ZeroTouchTelemetryAdapter:
    def status(self) -> Dict[str, str]:
        return {"status": "not_configured", "detail": "Collector automation not wired yet."}

    def plan_collectors(self, services: List[str]) -> Dict[str, str]:
        return {"status": "not_configured", "detail": "Collector plans will be generated by Project 5."}
