apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: storefront
  labels:
    app: checkout
spec:
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: ghcr.io/example/checkout:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: storefront
  labels:
    app: payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ghcr.io/example/payments:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: storefront
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: ghcr.io/example/inventory:latest
